name: flutter_statusbarcolor_ns
description: A package can help you to change your flutter app's statusbar's color or navigationbar's color programmatically.
version: 0.3.0-nullsafety
author: "Sameer <sameera.s.kashyap@gmail.com>"
homepage: https://github.com/Sameerkash/flutter_statusbarcolor

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.sameer.flutterstatusbarcolor.flutterstatusbarcolor
    pluginClass: FlutterStatusbarcolorPlugin

environment:
  sdk: '>=2.12.0-0<3.0.0'

